=== ashellwig/ashhellwig-spring/data/xml/Experience.dtd
<!ELEMENT Experience (company_name, start_date, end_date, job_title, job_summary, job_description, skills_required, detailed_achievements)>
<!ELEMENT company_name (#PCDATA)>
<!ELEMENT start_date (#PCDATA)>
<!ELEMENT end_date (#PCDATA)>
<!ELEMENT job_title (#PCDATA)>
<!ELEMENT job_summary (#PCDATA)>
<!ELEMENT job_description (#PCDATA)>
<!ELEMENT skills_required (#PCDATA)>
<!ELEMENT detailed_achievements (#PCDATA)>

=== ashellwig/ashhellwig-spring/data/xml/IBM.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Experience SYSTEM "Experience.dtd">
<Experience>
    <company_name>IBM</company_name>
    <start_date>2017-07-01</start_date>
    <end_date>2017-03-01</end_date>
    <job_title>0</job_title>
    <job_summary>Anthem Healthcare z/OS Mainframe Administrator and State Street</job_summary>
    <job_description>Level 1.5 CTS Agent, administrator rights to remote into State</job_description>
    <skills_required>z/OS, MVS, JCL, SDSF, VSAM, Endevor, SyncSort, MQSeries, SQL,</skills_required>
    <detailed_achievements>Master the Mainframe Part 2 Competitor</detailed_achievements>
</Experience>
